# Generated by Django 3.1.7 on 2021-05-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210504_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subtotal',
        ),
    ]
